### ISSUE TITLE
pi64-update progress bar

### ISSUE THREAD

**Issue by bamarni** [bamarni/pi64#28]
pi64-update downloads a ~50mb tarball, this can take some time so there should be a progress bar showing up.

**Comment by olle2** [comment]
Hi bamarni, that sounds like a good idea. I tried the pi64-update yesterday, and it downloaded the update slowly.

Afterwards, I had to re-configure the config.txt file. It reverted to contain the dtparam=audio=on only and I had to disable overscan and force turbo again. Is this intentional in the pi64 update process?

Keep up the good work! Olle

**Comment by bamarni** [comment]
Hi @olle2 ,

Thanks for reporting. Indeed the config.txt file shouldn't be part of the update tarball but in the distribution image only. I had this on the pipeline but didn't change it yet. I'll create an issue not to forget.
